export const CART_ACTION_TYPE = {
  SET_OPEN_DRAWER: "cart/SET_OPEN_DRAWER",
  ADD_TO_CART_DRAWER: "cart/ADD_TO_CART_DRAWER",
  REMOVE_FROM_CART_DRAWER: "cart/REMOVE_FROM_CART_DRAWER",
  ADD_TO_CART:"cart/ADD_TO_CART",
};